language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount

services:
 - xvfb

script: 
  - ./download_other_githubs
  # Console
  - qmake ApproximatorConsole.pro
  - make debug --silent
  - ./ApproximatorConsole
  # Desktop
  - qmake ApproximatorDesktop.pro
  - make debug --silent
  - ./ApproximatorDesktop &
  # helgrind
  - valgrind --tool=helgrind --log-file=helgrind.log -v ./ApproximatorConsole
  - cat helgrind.log
  # memcheck
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./ApproximatorConsole
  - cat memcheck.log
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint
  # Get my folder
  - my_github=${PWD##*/}  
  # SLOCcount
  - cd ..; sloccount --overhead 1 --personcost 22614 $my_github; cd $my_github

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
